# Generated by Django 3.1.6 on 2021-02-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Verbose_name', 'verbose_name_plural': 'Verbose_name_plural'},
        ),
    ]
