# Generated by Django 3.1.6 on 2021-02-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0005_auto_20210203_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='book_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Для пля Title', max_length=100, null=True),
        ),
    ]
