# Generated by Django 3.1.6 on 2021-02-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Суперзаголовок')),
            ],
            options={
                'verbose_name': 'Страница Flex',
                'verbose_name_plural': 'Страницы ',
            },
            bases=('wagtailcore.page',),
        ),
    ]
