# Generated by Django 3.1.6 on 2021-02-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Веедите Ваш email', max_length=100, verbose_name='Email')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
            ],
        ),
    ]
