# Generated by Django 3.1.6 on 2021-02-05 11:16

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('fuul_richtext', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
