# Generated by Django 3.1.6 on 2021-02-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0004_blogdetailpage_bloglistingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAvtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя и фамилия', max_length=100, verbose_name='Ф.И.О.')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Автор блога',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
